version: '3.3'
services:
  vernemq:
    build:
      context: .
    image: jbonachera/vernemq:v0.0.5-beta4
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - ALLOW_ANONYMOUS=on
      - SERVICE_NAME=vernemq
      - ALLOW_SUBSCRIBE_NETSPLIT=off
      - ALLOW_UNSUBSCRIBE_NETSPLIT=off
      - ALLOW_REGISTER_NETSPLIT=off
      - ALLOW_PUBLISH_NETSPLIT=off
    networks:
      - mqtt
    ports:
      - target: 1883
        published: 8883
        protocol: tcp
        mode: ingress
networks:
  mqtt:

