version: '3.3'
services:
  vernemq:
    build:
      context: .
    image: jbonachera/vernemq:v0.0.1
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - ALLOW_ANONYMOUS=on
      - SERVICE_NAME=vernemq
      - ALLOW_SUBSCRIBE_NETSPLIT=on
      - ALLOW_UNSUBSCRIBE_NETSPLIT=on
      - ALLOW_REGISTER_NETSPLIT=on
      - ALLOW_PUBLISH_NETSPLIT=on
    networks:
      - mqtt
    ports:
      - 1883
networks:
  mqtt:

